file = open("output.txt","w+")
a = input("Enter text to write to the file: ")
file.write(a+"\n")
file.seek(0)
read = file.read()
print(read)
b = input("Enter text to append: ")
file.write(b+"\n")
file.seek(0)
read = file.read()
print("Final content of output.txt:\n"+read)
file.close()
